import type { LayoutPreset, AspectRatio, TextAlign, LogoPosition, BgType } from "../store/quote-store";

export type TemplateConfig = {
	layoutPreset: LayoutPreset;
	aspectRatio: AspectRatio;
	accentColor: string;
	cardBgColor: string;
	cardTextColor: string;
	fontFamily: string;
	fontSize: number;
	textAlign: TextAlign;
	bgType: BgType;
	bgGradient: string;
	name: string;
	headline: string;
	logoOpacity: number;
	logoPosition: LogoPosition;
};

export type Template = {
	id: string;
	nameKey: string;
	descriptionKey: string;
	config: TemplateConfig;
};

export const TEMPLATES: Template[] = [
	{
		id: "elegant",
		nameKey: "editor.templateNames.elegant",
		descriptionKey: "editor.templateDescriptions.elegant",
		config: {
			layoutPreset: "classic",
			aspectRatio: "1:1",
			fontFamily: "'Playfair Display', serif",
			fontSize: 34,
			textAlign: "center",
			accentColor: "#c9a84c",
			cardBgColor: "#faf8f5",
			cardTextColor: "#2d2a24",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "sunset-vibes",
		nameKey: "editor.templateNames.sunsetVibes",
		descriptionKey: "editor.templateDescriptions.sunsetVibes",
		config: {
			layoutPreset: "bold-quote",
			aspectRatio: "4:5",
			fontFamily: "'Nunito', sans-serif",
			fontSize: 40,
			textAlign: "center",
			accentColor: "#f5576c",
			cardBgColor: "#fef3c7",
			cardTextColor: "#7c2d12",
			bgType: "gradient",
			bgGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "ocean-breeze",
		nameKey: "editor.templateNames.oceanBreeze",
		descriptionKey: "editor.templateDescriptions.oceanBreeze",
		config: {
			layoutPreset: "modern",
			aspectRatio: "1:1",
			fontFamily: "'Jost', sans-serif",
			fontSize: 28,
			textAlign: "left",
			accentColor: "#0ea5e9",
			cardBgColor: "#ffffff",
			cardTextColor: "#0c4a6e",
			bgType: "gradient",
			bgGradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "left",
		},
	},
	{
		id: "midnight",
		nameKey: "editor.templateNames.midnight",
		descriptionKey: "editor.templateDescriptions.midnight",
		config: {
			layoutPreset: "minimal",
			aspectRatio: "1:1",
			fontFamily: "'Space Grotesk', sans-serif",
			fontSize: 36,
			textAlign: "center",
			accentColor: "#818cf8",
			cardBgColor: "#0f172a",
			cardTextColor: "#e2e8f0",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "earthy",
		nameKey: "editor.templateNames.earthy",
		descriptionKey: "editor.templateDescriptions.earthy",
		config: {
			layoutPreset: "classic",
			aspectRatio: "1.91:1",
			fontFamily: "'Merriweather', serif",
			fontSize: 30,
			textAlign: "left",
			accentColor: "#65a30d",
			cardBgColor: "#f7fee7",
			cardTextColor: "#3f6212",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "playful",
		nameKey: "editor.templateNames.playful",
		descriptionKey: "editor.templateDescriptions.playful",
		config: {
			layoutPreset: "modern",
			aspectRatio: "4:5",
			fontFamily: "'Poppins', sans-serif",
			fontSize: 32,
			textAlign: "center",
			accentColor: "#ec4899",
			cardBgColor: "#fce7f3",
			cardTextColor: "#831843",
			bgType: "gradient",
			bgGradient: "linear-gradient(135deg, #fddb92 0%, #d1fdff 100%)",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "center",
		},
	},
	{
		id: "luxury",
		nameKey: "editor.templateNames.luxury",
		descriptionKey: "editor.templateDescriptions.luxury",
		config: {
			layoutPreset: "bold-quote",
			aspectRatio: "1:1",
			fontFamily: "'Cormorant Garamond', serif",
			fontSize: 42,
			textAlign: "center",
			accentColor: "#b8860b",
			cardBgColor: "#1a1a1a",
			cardTextColor: "#f5f5dc",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "pastel-dream",
		nameKey: "editor.templateNames.pastelDream",
		descriptionKey: "editor.templateDescriptions.pastelDream",
		config: {
			layoutPreset: "classic",
			aspectRatio: "9:16",
			fontFamily: "'Lora', serif",
			fontSize: 30,
			textAlign: "center",
			accentColor: "#a78bfa",
			cardBgColor: "#ede9fe",
			cardTextColor: "#3b0764",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "center",
		},
	},
	{
		id: "neon-pulse",
		nameKey: "editor.templateNames.neonPulse",
		descriptionKey: "editor.templateDescriptions.neonPulse",
		config: {
			layoutPreset: "minimal",
			aspectRatio: "1:1",
			fontFamily: "'Work Sans', sans-serif",
			fontSize: 38,
			textAlign: "center",
			accentColor: "#22d3ee",
			cardBgColor: "#042f2e",
			cardTextColor: "#ccfbf1",
			bgType: "gradient",
			bgGradient: "linear-gradient(135deg, #0c3483 0%, #a2b6df 100%)",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "vintage-paper",
		nameKey: "editor.templateNames.vintagePaper",
		descriptionKey: "editor.templateDescriptions.vintagePaper",
		config: {
			layoutPreset: "classic",
			aspectRatio: "4:5",
			fontFamily: "'Fraunces', serif",
			fontSize: 32,
			textAlign: "left",
			accentColor: "#a16207",
			cardBgColor: "#fffbeb",
			cardTextColor: "#451a03",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "forest-mist",
		nameKey: "editor.templateNames.forestMist",
		descriptionKey: "editor.templateDescriptions.forestMist",
		config: {
			layoutPreset: "modern",
			aspectRatio: "1.91:1",
			fontFamily: "'DM Sans', sans-serif",
			fontSize: 28,
			textAlign: "center",
			accentColor: "#22c55e",
			cardBgColor: "#052e16",
			cardTextColor: "#bbf7d0",
			bgType: "gradient",
			bgGradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "clean-white",
		nameKey: "editor.templateNames.cleanWhite",
		descriptionKey: "editor.templateDescriptions.cleanWhite",
		config: {
			layoutPreset: "minimal",
			aspectRatio: "1:1",
			fontFamily: "'Plus Jakarta Sans', sans-serif",
			fontSize: 30,
			textAlign: "left",
			accentColor: "#64748b",
			cardBgColor: "#ffffff",
			cardTextColor: "#0f172a",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
	{
		id: "royal",
		nameKey: "editor.templateNames.royal",
		descriptionKey: "editor.templateDescriptions.royal",
		config: {
			layoutPreset: "bold-quote",
			aspectRatio: "1:1",
			fontFamily: "'Merriweather', serif",
			fontSize: 36,
			textAlign: "center",
			accentColor: "#7c3aed",
			cardBgColor: "#2e1065",
			cardTextColor: "#e9d5ff",
			bgType: "solid",
			bgGradient: "",
			name: "",
			headline: "",
			logoOpacity: 0.5,
			logoPosition: "right",
		},
	},
];
